apiVersion: v1
appVersion: 1.0.1
deprecated: true
description: DEPRECATED A Helm chart for prometheus node-exporter
home: https://github.com/prometheus/node_exporter/
keywords:
- node-exporter
- prometheus
- exporter
name: prometheus-node-exporter
sources:
- https://github.com/prometheus/node_exporter/
version: 1.11.2
