kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: {{ .Release.Namespace }}
data:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
      smtp_from: '{{.Values.smtpFrom}}'
      smtp_smarthost: '{{.Values.smtpHost}}:{{.Values.smtpPort}}'
      smtp_auth_username: '{{.Values.smtpUser}}'
      smtp_auth_password: '{{.Values.smtpPassword}}'
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: email
    receivers:
    - name: email
      email_configs:
      - to: '{{.Values.to_mail}}'
        headers:
          subject: "K8S Cluster Name={{ .Values.clusterName}} {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        text: "{{ range .Alerts }}\n{{ end }}"
        #text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'cluster', 'service']