apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.19.0
        args:
          - "--config.file=/etc/alertmanager/config/alertmanager.yaml"
          - "--storage.path=/alertmanager"
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager/config/alertmanager.yaml
          subPath: alertmanager.yaml
          readOnly: true
        - name: alertmanager
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
      - name: alertmanager
        emptyDir: {}
      # nodeSelector:
      #   kubernetes.azure.com/scalesetpriority: "spot"
      # tolerations:
      # - key: "kubernetes.azure.com/scalesetpriority"
      #   operator: "Equal"
      #   value: "spot"
      #   effect: "NoSchedule"
{{ if .Values.imagePullSecretName }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecretName }}
{{end }}       
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: alertmanager  
  ports:
    - port: 9093
      targetPort: 9093
      protocol: TCP